### ISSUE TITLE
This does not work on Windows Forms.

### ISSUE THREAD

**Issue by Pronner** [CmlLib/CmlLib.Core.Auth.Microsoft#11]
I've tried this on a .NET Windows Forms app and it didnt do anything when I clicked button1.
```cs
using CmlLib.Core;
using CmlLib.Core.Auth;
using CmlLib.Core.Auth.Microsoft;
using CmlLib.Core.Auth.Microsoft.UI.WinForm;
using Microsoft.Extensions.Logging;
using Microsoft.Web.WebView2.Core;
using Newtonsoft.Json;
using System;
using System.ComponentModel;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using XboxAuthNet.OAuth;
using XboxAuthNet.XboxLive;

namespace ElixirClient
{
    public partial class Form1 : Form
    {
        MSession Session;

        public Form1()
        {
            InitializeComponent();
        }

        private async Task<MicrosoftLoginForm> CreateForm()
        {
            var loginHandler = new LoginHandler();
            MicrosoftLoginForm form = new MicrosoftLoginForm(loginHandler);

            //var dataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "CmlLib.Core.Auth.Microsoft.UI.WinForm.TestApp");
            //form.WebView2Environment = await CoreWebView2Environment.CreateAsync(userDataFolder: dataPath);

            return form;
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            var form = await CreateForm();

            try
            {
                MSession session = await form.ShowLoginDialog(); // show login form
                this.Session = session;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        private async void btnLogout_Click(object sender, EventArgs e)
        {
            MicrosoftLoginForm form = await CreateForm();
            form.ShowLogoutDialog(); // show logout form

            MessageBox.Show("Done");
        }

        private async void btnStart_Click(object sender, EventArgs e)
        {

            var path = new MinecraftPath(); // default game path
            var launcher = new CMLauncher(path);

            // register event handlers
            launcher.FileChanged += Launcher_FileChanged;
            launcher.ProgressChanged += Launcher_ProgressChanged;

            // check and download game files
            var process = await launcher.CreateProcessAsync("1.18.2", new MLaunchOption
            {
                Session = this.Session,
                MaximumRamMb = 4096
            });

            // start game
            process.Start();
        }

        private void Launcher_FileChanged(CmlLib.Core.Downloader.DownloadFileChangedEventArgs e)
        {

        }

        private void Launcher_ProgressChanged(object sender, ProgressChangedEventArgs e)
        {
        }
    }
}

```

**Comment by Pronner** [comment]
Nevermind, I just had to log out. Sorry!

**Comment by Pronner** [comment]
Nevermind, I got an error
![image](https://user-images.githubusercontent.com/84229419/184554497-f4546f4f-630a-4390-9354-7db3f5bfac9c.png)

No Idea what to do

**Comment by Pronner** [comment]
> Nevermind, I got an error ![image](https://user-images.githubusercontent.com/84229419/184554497-f4546f4f-630a-4390-9354-7db3f5bfac9c.png)
> 
> No Idea what to do

Line 194: MSession session = await form.ShowLoginDialog();

**Comment by Pronner** [comment]
I think it doesn't support .NET, not Windows Forms but not 100% sure. I need the fix asap!

**Comment by AlphaBs** [comment]
this may related to WebView2 issue.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2447

**Comment by Pronner** [comment]
I just checked that issue and I'm still not sure what to do...

**Comment by Pronner** [comment]
I've tried reverting back to an older version (1.0.1210.39) and got a different error this time "System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.
"

**Comment by AlphaBs** [comment]
I've seen very similar issues on another project.

it was made on .net framework and uses Fody.Costura.

StackOverflowException was related to Fody.Costura. Costura was not able to load webview2 library and it retry infinitely.

As I remember, I solved this by removing all nuget package and reinstall only one package: CmlLib.Core.Auth.Microsoft.UI.Winform (or Wpf), and I removed app.config file in my project.


btw webview2 is so buggy actually i don't want to maintain UI.Winform and UI.Wpf package.  CmlLib.Core.Auth.Microsoft.MsalClient provides more options to login without any webview2 related bugs.

**Comment by Pronner** [comment]
Oh, then that explains it.
I use Costura.Fody and I guess that's why it's happening. Anyways, i've found another way to authenticate accounts via Microsoft Login, but thank you for letting me know what the issue is from. I recommend you switch from WebView2 to some other package cause from what i've heard and what you said it's really buggy.
