### ISSUE TITLE
How to specify custom error message when a user's account is error and how to bypass restriction for children and teens who are not in Family Group?

### ISSUE THREAD

**Issue by evcode17** [CmlLib/CmlLib.Core.Auth.Microsoft#12]
So, I've tested this library with my another account and I got an error (https://start.ui.xboxlive.com/AddChildToFamily) because I'm under 18. My question is how to display custom error message for general users (e.g. "You're under 18 and need to be added to a Family")? Because they may not understand what the error message means. 

Also my last question is, "How to allow children and teens under 18 to play Minecraft with my launcher without having to join a Family Group?" 😄 You can learn more from this link: https://github.com/XboxReplay/xboxlive-auth/blob/master/docs/07-Detect_Unauthorized_AgeGroup.md

Thank you.

**Comment by AlphaBs** [comment]
I'm using `Error` property of `XboxAuthException` to specify error.

```csharp
try
{
    // login codes
}
catch (XboxAuthException ex)
{
            var error = ex.Error?.Trim()?.ToLowerInvariant();
            if (error == "8015dc09")
                msg = "you don't have xbox profile";
            else if (error == "8015dc0b")
                msg = "country ban";
            else if (error == "8015dc0c" || error == "8015dc0d")
                msg = "need age verification";
            else if (error == "8015dc0e")
                msg = "need to be added to a familly";
}
```

**Comment by evcode17** [comment]
How about my last question? haha

**Comment by AlphaBs** [comment]
oh I didn't know that there is a way to bypass age detection. I think I can add this on the next version.

Thank you for letting me know.

**Comment by evcode17** [comment]
OK, thank you. If this successfully, my launcher will be used by many children and teens. But actually in my region there is no rules given by Microsoft about their Family features. I can actually use my alt account to create a Family Group and invite my primary account to join my Family Group, ALL WITHOUT ENTERING A FAKE BIRTHDAY INTO ANY ACCOUNT, AMAZING!

**Comment by evcode17** [comment]
So other children may use that trick and they don't have to break Microsoft's rules. Just by creating 2 Microsoft Account with their real birthday. I don't know in other region.

**Comment by evcode17** [comment]
But it's more amazing when you add that feature. Because they'll be able to play only with 1 Microsoft Account.

**Comment by evcode17** [comment]
Have you done doing this?

**Comment by evcode17** [comment]
What things to concern other than device token?

**Comment by AlphaBs** [comment]
first we need device token and user token, and send this tokens to sisu.xboxlive.com.
all messaage should be signed with ECDSA key. 

I have implemented all of this but there are some problems:

1. generating key pair does not always succeed.

I used Bouncycastle library to generate EC key pair with P-256 curve, which is same algorithm used by prismarine-auth. however xbox server does not always accept my request. it returns 403: forbidden. 

2. MsalClient can't bypass age detection

To bypass age detection, you should authenticate by sisu.xboxlive.com. however, you can' use custom azure client app id in this way, which MsalClient uses

**Comment by evcode17** [comment]
So we can't use MsalClient? Why we should authenticate with sisu.xboxlive.com? I also have tried to call the device authentication api myself, but it's return 403: forbidden.

**Comment by evcode17** [comment]
Ah I know, we only need to change the XSTS Authorization URL to sisu authorization URL and generate a device token, is that correct? Or we need more steps?

**Comment by evcode17** [comment]
Also we can't use MsalClient but we can use custom client id, is that correct?

**Comment by evcode17** [comment]
Also we can't use MsalClient but we can use custom client id, is that correct?

**Comment by AlphaBs** [comment]
> Ah I know, we only need to change the XSTS Authorization URL to sisu authorization URL and generate a device token, is that correct? Or we need more steps?

yes. but sisu.xboxlive.com does not accept access token from custom client id. that's why we can' use MsalClient

**Comment by evcode17** [comment]
OK, my question, why we need to use sisu.xboxlive.com to bypass age detection? Can just we generate device token and use the normal XSTS Authorization URL.

**Comment by evcode17** [comment]
Have you tried using custom client id?

**Comment by AlphaBs** [comment]
yes i tried

custom client id + sisuauth -> 401
custom client id + devicetoken -> underage error
custom client id + devicetoken + titletoken -> 401

java edition client id + sisuauth -> success

**Comment by evcode17** [comment]
Have you tried java edition client id + device token + normal xsts auth? Make sure to use a Microsoft Account belonging to someone under the age of 18 who hasn't joined a Family Group when you test this!

**Comment by evcode17** [comment]
> custom client id + devicetoken -> underage error

Isn't this used in the `XboxReplay/xboxlive-auth` library? Why underage error happening? Isn't the `XboxReplay/xboxlive-auth` library use the normal XSTS auth but with Device Token? Or I'm wrong?

**Comment by evcode17** [comment]
I've tried today using normal XSTS flow with a Device Token generated from `xboxlive-auth` node.js library with my account without family and it success (my age is under 18).

**Comment by evcode17** [comment]
But if with your Device Token failed, then try using sisu.xboxlive.com.

**Comment by AlphaBs** [comment]
> I've tried today using normal XSTS flow with a Device Token generated from `xboxlive-auth` node.js library with my account without family and it success (my age is under 18).

There are 3 types of age-related errors: 8015dc0c, 8015dc0d, 8015dc0e. I've seen many user of my launcher get these 3 errors a lot, so I want to solve all of age-related problems.

this is login flow much detail:

1. Currently cmllib do this flow
`custom client id -> oauth(MsalClient) -> usetoken -> xsts`
`java edition client id -> oauth(WebView2) -> usertoken -> xsts`

8015dc0c, 8015dc0d, 8015dc0e, all occurs


2. add device token
`custom client id -> oauth(MsalClient) -> usetoken -> devicetoken -> xsts`
`java edition client id -> oauth(WebView2) -> usertoken -> devicetoken -> xsts`

8015dc0e solved, but still 8015dc0c, 8015dc0d occurs
if you only need to bypass 8015dc0e (need to add to family group), I already have done this.


3. add title token
`custom client id -> oauth(MsalClient) -> usetoken -> devicetoken -> titletoken -> xsts`
`java edition client id -> oauth(WebView2) -> usertoken -> devicetoken -> titletoken -> xsts`

403: forbidden while requesting titletoken

4. use sisuauth
`custom client id -> oauth(MsalClient) -> devicetoken -> sisuauth`

error code 0xffffffff or 401: Unauthorized

`java edition client id -> oauth(WebView2) -> devicetoken -> sisuauth`

8015dc0c, 8015dc0d, 8015dc0e, all problems are solved!

**Comment by evcode17** [comment]
What's the means of 8015dc0d, 8015dc0e (other than need to add to family group) error?

**Comment by evcode17** [comment]
Is the 8015dc0d, 8015dc0e South Korea age verification problem?

**Comment by AlphaBs** [comment]
In some countries, if you don't verify your age or you're under 18, you'll always get an error, regardless of your family group.

yes, south korea age verification

**Comment by evcode17** [comment]
Does the South Korea shutdown law still there so it require users to be at least 19 years old?

**Comment by AlphaBs** [comment]
That law was repealed.  However, it seems that Microsoft's restrictions on Korean 18-year-old users have not completely disappeared.

**Comment by evcode17** [comment]
Why they isn't completely disappeared, the law was abolished since 2021 (almost 1 year and Microsoft still hasn't take action)? So it's fine if I bypass it?

**Comment by evcode17** [comment]
When your users get the age verification error? on this year?

**Comment by AlphaBs** [comment]
> Why they isn't completely disappeared, the law was abolished since 2021 (almost 1 year and Microsoft still hasn't take action)? So it's fine if I bypass it?

I don't know they still restrict it.

This is real error log:
![image](https://user-images.githubusercontent.com/17783561/187057873-4788d554-9f86-4685-9d9b-b6da96ac107d.png)

It happens very often:

![image](https://user-images.githubusercontent.com/17783561/187057945-40f57037-eb75-40d4-a36f-3f7d8b113b78.png)

**Comment by AlphaBs** [comment]
> Why they isn't completely disappeared, the law was abolished since 2021 (almost 1 year and Microsoft still hasn't take action)? So it's fine if I bypass it?

the users under 18 in south korea they must login with sisu.xboxlive.com. it's the only way to bypass age restriction

**Comment by evcode17** [comment]
Have you added this to the library?

**Comment by AlphaBs** [comment]
I'm working on `dev` branch

> Have you added this to the library? And how to authenticate with WebView2 without cookie, so the user must login every time (like in the official (old) Minecraft Launcher) where if you click "Add Account" or something similar, it always prompt you to login.

9372e35a7be4119a3e3cbfbafc6fa9c7866930bb done

**Comment by evcode17** [comment]
Why just on dev branch? When you pull to nuget?

**Comment by AlphaBs** [comment]
I'm testing now. testing, writing a document, and finally releasing a new version

**Comment by AlphaBs** [comment]
release 2.1.0-rc

document: https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/tree/dev/docs

**Comment by AlphaBs** [comment]
you can't extend partial class of other assembly. why do you need?

**Comment by evcode17** [comment]
Because I need to also store Microsoft ID Token. Can you help me?

**Comment by evcode17** [comment]
Also I want to add some things myself for the 'MicrosoftOAuthResponse'.

**Comment by AlphaBs** [comment]
`MicrosoftOAuthResponse` is the part of `XboxAuthNet`. You need to modify `XboxAuthNet`.


Can you tell me more detail about Microsoft ID? If you can I can update the library to be extendible as you need.

**Comment by evcode17** [comment]
You need to add this:

```cs
[JsonPropertyName("expires_on")]
public DateTimeOffset ExpiresOn { get; set; }
[JsonPropertyName("id_token")]
public string? IdToken { get; set; }
[JsonPropertyName("user_data")]
public MicrosoftUserPayload? UserData { get; set; }
```
'MicrosoftUserPayload' class:
```cs
[JsonPropertyName("iss")]
public string? Issuer { get; set; }
[JsonPropertyName("oid")]
public string? UserId { get; set; }
[JsonPropertyName("aud")]
public string? ApplicationId { get; set; }
[JsonPropertyName("exp")]
public long? ExpiresOn { get; set; }
[JsonPropertyName("iat")]
public long? IssuedAt { get; set; }
[JsonPropertyName("nbf")]
public long? NotBefore { get; set; }
[JsonPropertyName("name")]
public string? Name { get; set; }
[JsonPropertyName("preferred_username")]
public string? Username { get; set; }
[JsonPropertyName("email")]
public string? Email { get; set; }
```

**Comment by evcode17** [comment]
Have you done doing this? It's not difficult right? You just need to add some property to class.

**Comment by AlphaBs** [comment]
okay please don't rush me. I can't afford to focus on this project right now. how about making PR? 

https://github.com/AlphaBs/XboxAuthNet/tree/dev

**Comment by evcode17** [comment]
Wait wait

**Comment by evcode17** [comment]
Sorry! I've make a pull request. Please accept it. Are you working of another project?

**Comment by AlphaBs** [comment]
yes. I don't have much time now :(  
I'm sorry I couldn't fully support you.

**Comment by evcode17** [comment]
It's fine if you don't have much time. Because actually my launcher doesn't have a users for now, so it's also for my experiment! So you can do this project with little bit relaxed!

**Comment by evcode17** [comment]
Please review my pull request again if you have a time. Thank you.
