### ISSUE TITLE
MsalClient open WebView even if I'm not specifying it

### ISSUE THREAD

**Issue by evcode17** [CmlLib/CmlLib.Core.Auth.Microsoft#13]
I'm trying to use 'CreateInteractiveApi' method of my custom factory which I've copied from this library and paste it, but it's not opening system web browser but opening WebView? Can you fix this?

**Comment by AlphaBs** [comment]
Using a system web browser or WebView2 is determined by MSAL.NET. 

If MSAL.NET couldn't open WebView2, it will open a system web browser.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#availability-per-platform

**Comment by evcode17** [comment]
This issue is now solved. MSAL.NET default web browser is embedded and I have changed that and it's now opening system browser.
