### ISSUE TITLE
Cannot find `MsalMinecraftLoginHandler`

### ISSUE THREAD

**Issue by MasterYuan418** [CmlLib/CmlLib.Core.Auth.Microsoft#15]
Error message:
`The type or namespace name 'MsalMinecraftLoginHandler' could not be found (are you missing a using directive or an assembly reference?)`

Usings:
using CmlLib.Core.Auth.Microsoft.MsalClient;
using CmlLib.Core.Auth;
using Microsoft.Identity.Client;

**Comment by JamDoggie** [comment]
Same issue here. Seems the docs aren't up to date.

**Comment by lemonekq** [comment]
looks like you both dont have that nuget package installed

CmlLib.Core.Auth.Microsoft

**Comment by AlphaBs** [comment]
all docs and packages were updated now. sorry for delay :(
