### ISSUE TITLE
Please support Xamarin as well as winform and wpf

### ISSUE THREAD

**Issue by newkincode** [CmlLib/CmlLib.Core.Auth.Microsoft#17]
If so, you can log in using the webview on a Mac.

**Comment by AlphaBs** [comment]
use [XboxAuthNet.Game.Msal](https://alphabs.gitbook.io/cmllib/auth.microsoft/xboxauthnet.game.msal)

[JELoginHandler](https://alphabs.gitbook.io/cmllib/auth.microsoft/cmllib.core.auth.microsoft/jeloginhandler#2.-oauth)
