### ISSUE TITLE
Failed to log in: Invalid Session (Try restarting your game and the launcher)

### ISSUE THREAD

**Issue by voidZiAD** [CmlLib/CmlLib.Core.Auth.Microsoft#20]
This issue stems from I'm guessing:

The session of the user eventually expires after logging in? if so, why? and how can I make sure that he doesn't have to log in every 24h or so?

This account is a Microsoft Account that I've bought minecraft java with, and I'm trying to join pvplegacy & hypixel but it's not working. The last time I logged in was yesterday. I'm currently still logged in, but when I launch the game and join — it doesn't let me connect and actually join the server.

I want to know how I can re-create a session for the user whether he has a Microsoft account or a Mojang account. It's simply not sustainable for me to ask the user to re-log in every day. It's annoying.

![image](https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/assets/84229419/c3f733d4-a7ce-462d-a590-83b544fc0bd8)

**Comment by voidZiAD** [comment]
I just attempted to do the following:

```cs
session = new MSession(Properties.Settings.Default.SessionInfo.Username, Properties.Settings.Default.SessionInfo.AccessToken, Properties.Settings.Default.SessionInfo.UUID);
Properties.Settings.Default.SessionInfo = session;
Properties.Settings.Default.Save();
var result = session.CheckIsValid;
```

But that didn't work, so I'm not sure what else will work

**Comment by voidZiAD** [comment]
okay, I fixed it.
All I had to do was:

```cs
 var loginHandler = JELoginHandlerBuilder.BuildDefault();
 session = await loginHandler.Authenticate();
 Properties.Settings.Default.SessionInfo = session;  // Optional, I just need it in my case
 Properties.Settings.Default.Save(); // Optional, I just need it in my case
```

and for Mojang Legacy Accounts:

```cs
response = login.Authenticate("email", "password");
```

Refer to the docs if you had this issue and are reading this:

https://alphabs.gitbook.io/cmllib/cmllib.core/login-and-sessions/mojang-account
https://alphabs.gitbook.io/cmllib/auth.microsoft/cmllib.core.auth.microsoft

it'd be cool to pin this as well
looks like I'm just making issues to solve them myself 😂

**Comment by M1XT3NZ** [comment]
Actually mojang accounts don’t really exist anymore 🤷‍♂️

**Comment by voidZiAD** [comment]
Oh. Well I guess the microsoft one still works at least

**Comment by AlphaBs** [comment]
you don't need to implement saving a session. the library already do this. all code you need is:
```csharp
var loginHandler = JELoginHandlerBuilder.BuildDefault();
session = await loginHandler.Authenticate();
```

`Authenticate()` method loads saved accounts and try to authenticate with the most recently used account. and also refresh the tokens if the session is expired.

List saved accounts:
https://alphabs.gitbook.io/cmllib/auth.microsoft/cmllib.core.auth.microsoft/jeloginhandler#list-accounts

**Comment by voidZiAD** [comment]
Oh. Bet!
Thank you, I'll keep that in mind. Can you also please check my issue on CmlLib.Core?
