### ISSUE TITLE
Signout from account do not remove it

### ISSUE THREAD

**Issue by ItsTheSky** [CmlLib/CmlLib.Core.Auth.Microsoft#21]
Hi there!
After login-in with my JELoginHandler via Msal, when I try to logout/signout from an account, it just does not work, no exceptions happen, and the account is still connected and can still be used.
Funny enough, I can use `LoginHandler.AccountManager.ClearAccounts()` to remove **all** connected account, and here it works fine. 
Do I miss something and I have to do another thing before removing an account?
Thanks!

**Comment by AlphaBs** [comment]
can you post your login / signout code?

**Comment by ItsTheSky** [comment]
This is the code for login:
```java
var authenticator = LoginHandler.CreateAuthenticatorWithNewAccount();
authenticator.AddMsalOAuth(ClientApplication, msal => msal.Interactive());
authenticator.AddXboxAuthForJE(xbox => xbox.Basic());
authenticator.AddForceJEAuthenticator();
var task = authenticator.ExecuteForLauncherAsync();
session = await task;
```
(Where `LoginHandler` is a JELoginHandler)
And this one is for signing out:
```java
await _loginHandler.Signout(_account);
_loginHandler.AccountManager.SaveAccounts();
```
(Where `_account` is a XboxGameAccount, and `_loginHandler` the same handler as the previous code)

**Comment by AlphaBs** [comment]
I can't reproduce the issue. can you explain more detail information? what do you mean 'the account is still connected'? 
- the account is still presence when you call `loginHandler.AccountManager.GetAccounts()` ?
- the account in browser was not removed?

**Comment by ItsTheSky** [comment]
Here's the full code that I'm using to reload displayed accounts. (GameAccount is a custom class, holding a JEGameAccount):
```csharp
    public async void ReloadAccounts()
    {
        AccountsRepeater.ItemsSource = null;
        
        var array = new List<GameAccount>();
        var loginHandler = MainWindow.Instance.LoginHandler;
        foreach (var account in loginHandler.AccountManager.GetAccounts())
        {
            if (account is not JEGameAccount xboxGameAccount) 
                continue;
            
            var gameAccount = new GameAccount(loginHandler, xboxGameAccount);
            
            await gameAccount.TryLoadAccount();
            if (!gameAccount.IsUsable)
            {
                await loginHandler.Signout(account);
                continue;
            }
            
            array.Add(gameAccount);
        }
        
        // Offline Accounts
        foreach (var offlineUsername in GameAccount.OfflineUsernames)
        {
            var gameAccount = new GameAccount(loginHandler, offlineUsername);
            await gameAccount.TryLoadAccount();
            array.Add(gameAccount);
        }

        if (MainWindow.Instance.SelectedAccount == null && array.Count > 0) {
            MainWindow.Instance.SelectedAccount = array[0].Session;
            await MainWindow.Instance.RefreshAccountDisplay();
        }
        
        AccountsRepeater.ItemsSource = array.ToArray();
    }
```
And here's the full code used to remove a GameAccount:
```csharp
await _loginHandler.Signout(_account);
_loginHandler.AccountManager.SaveAccounts();
await MainWindow.Instance.LoadAccount();
AccountsWindow.Instance?.Close();
```
By "still connected" I mean even after calling `Signout` on any account, the size of `loginHandler.AccountManager.GetAccounts()` is not changed.

> the account is still presence when you call loginHandler.AccountManager.GetAccounts() ?
Yup, same size and when looping it's still here, even right after the Signout call
> the account in browser was not removed?
Do you mean when MSAL opens the browser? If yes then yes they are still connected, but it's my microsofts accounts that are connected on my web browser.

**Comment by AlphaBs** [comment]
can you run below code on your machine? 

```csharp
using CmlLib.Core.Auth.Microsoft;
using Microsoft.Identity.Client;
using XboxAuthNet.Game.Msal;

IPublicClientApplication? app = await MsalClientHelper.BuildApplicationWithCache("499c8d36-be2a-4231-9ebd-ef291b7bb64c");
var loginHandler = JELoginHandlerBuilder.BuildDefault();

// list accounts
foreach (var account in loginHandler.AccountManager.GetAccounts())
{
    Console.WriteLine("account " + account.Identifier);
}

// authenticate
var authenticator = loginHandler.CreateAuthenticatorWithNewAccount();
authenticator.AddMsalOAuth(app, msal => msal.Interactive());
authenticator.AddXboxAuthForJE(xbox => xbox.Basic());
authenticator.AddForceJEAuthenticator();
var result = await authenticator.ExecuteForLauncherAsync();
Console.WriteLine(result.Username);

// signout all accounts
foreach (var account in loginHandler.AccountManager.GetAccounts())
{
    Console.WriteLine("signout " + account.Identifier);
    await loginHandler.Signout(account);
}

// list accounts
foreach (var account in loginHandler.AccountManager.GetAccounts())
{
    Console.WriteLine("account " + account.Identifier);
}

Console.WriteLine("done");
```

it should print:

![image](https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/assets/17783561/3241c379-bb4c-4aa7-81ef-e7a9cec8b9f2)

**Comment by ItsTheSky** [comment]
I just tried the code you gave me and indeed it seems to work fine here 😭
![image](https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/assets/50667548/8bb4da3b-bf4a-400f-b49e-5b4f7b752750)
Do you know any advice on why it could not remove the account correctly? (like what are the usual reasons) I bet it's on my end code it's broken, but I definitely don't see where it could come from

**Comment by AlphaBs** [comment]
when does your launcher initialize `loginHandler`?

maybe using two instances of loginHandler causes the issue. make loginHandler singleton object and try again.

**Comment by ItsTheSky** [comment]
Hum, I indeed only create the instance once on my main method, which is run only one time.
Just thought about this, but if we have "cached" (created) a session via an account, may that interfere with signing out from the account? Explaining why I cannot remove the account yet, as a session is loaded with that account.

**Comment by AlphaBs** [comment]
No. creating a session doesn't affect an account in any way. it just reads some values from the account.
I've tried various tests, but it seems difficult to debug this issue. How about setting a breakpoint on the line that calls array.Add() to see what values are added?

**Comment by ItsTheSky** [comment]
I'll debug everything as I'm a bit lost now 😭
Would you be willing in additions to take a look at a private repo for the code?

**Comment by AlphaBs** [comment]
sure

**Comment by ItsTheSky** [comment]
Ahh sorry, in the end, I am reworking my whole project as the code was too messy. For now, I don't have this issue anymore with my new code, I'll come back here if you wish if I have it in the future!
