### ISSUE TITLE
[Feature request] AvaloniaUI support

### ISSUE THREAD

**Issue by MelonHell** [CmlLib/CmlLib.Core.Auth.Microsoft#3]
since wpf and winforms are only available for windows, I would like avalonia support for a cross-platform launcher

**Comment by AlphaBs** [comment]
use `CmlLib.Core.Auth.Microsoft.UI.MsalClient` for another platform.  
It will be added after the demand for Avalonia UI increases and the current UI library stabilizes.

**Comment by CaptaiNiveau** [comment]
We need this as well

**Comment by newkincode** [comment]
CmlLib.Core.Auth.Microsoft.UI.MsalClient may be unusable due to errors (that includes me)

**Comment by AlphaBs** [comment]
use this [XboxAuthNet.Game.Msal](https://alphabs.gitbook.io/cmllib/auth.microsoft/xboxauthnet.game.msal)
