### ISSUE TITLE
method not found error 

### ISSUE THREAD

**Issue by Angel36912** [CmlLib/CmlLib.Core.Auth.Microsoft#8]
I compiled the winform example of authentication with all packages needed but i received an error 
"Method not found"

adjunt screenshots
![image](https://user-images.githubusercontent.com/57499640/178406403-3e7c1a81-4d61-4e4e-b580-d6a0a6e1f5db.png)

**Comment by AlphaBs** [comment]
remove nuget package:
```
CmlLib.Core.Auth.Microsoft.UI.WinForm
CmlLib.Core.Auth.Microsoft.UI.Wpf
CmlLib.Core.Auth.Microsoft
XboxAuthNet
Microsoft.Web.WebView2
```

and reinstall only `CmlLib.Core.Auth.Microsoft.UI.WinForm` package

**Comment by Angel36912** [comment]
> remove nuget package:
> 
> ```
> CmlLib.Core.Auth.Microsoft.UI.WinForm
> CmlLib.Core.Auth.Microsoft.UI.Wpf
> CmlLib.Core.Auth.Microsoft
> XboxAuthNet
> Microsoft.Web.WebView2
> ```
> 
> and reinstall only `CmlLib.Core.Auth.Microsoft.UI.WinForm` package
> 
> example project will be updated soon

tnx the form is working now
