### ISSUE TITLE
Get XSTS not working when RelyingParty is http://xboxlive.com

### ISSUE THREAD

**Issue by evcode17** [CmlLib/CmlLib.Core.Auth.Microsoft#9]
I use this library and I'm trying to also get user's Xbox Live Profile info for my needs, but when the RelyingParty is http://xboxlive.com 
it throws XboxAuthException (maybe) and the success XSTS token result is the exception message. Like what? It success but it throws exception and a success result is the message. Can you fix this?

**Comment by AlphaBs** [comment]
can you attach your code?

**Comment by evcode17** [comment]
I'm customising LoginHandler and this is the LoginFromOAuth code:

```
public virtual async Task<SessionCacheData> LoginFromOAuth(MicrosoftOAuthResponse msToken)
        {
            var xsts = await GetXsts(msToken);

            var xstsXboxLive = await GetXsts(msToken, "http://xboxlive.com"); // it throws exception when RelyingParty is http://xboxlive.com
            var mojangToken = await GetMojangXboxToken(xsts);
            var msession = await GetMSession(mojangToken, new MSession());
            var sessionCache = new SessionCacheData
            {
                MicrosoftOAuthToken = msToken,
                XstsToken = xsts,
                MojangXboxToken = mojangToken,
                GameSession = msession,
                LiveXstsToken = xstsXboxLive,
            };
            saveSessionCache(sessionCache);
            return sessionCache;
        }
```

**Comment by evcode17** [comment]
Are there any fix?

**Comment by AlphaBs** [comment]
fixed. update package `XboxAuthNet` to `2.1.0`

**Comment by evcode17** [comment]
OK, it worked. Thank you very much! Before this fixed, I use the Minecraft Access Token to authenticate with my API then decode the token to get the XUID, and now I can DIRECTLY get the user's Xbox Live Profile. Awesome!
